-- seed-products.sql
-- No seed data — add your Rudraksha products via the Admin Panel.
--
-- To clear ALL existing products and related data from your Supabase DB:
--
--   DELETE FROM order_items;
--   DELETE FROM cart;
--   DELETE FROM wishlist;
--   DELETE FROM products;
--
-- Then add new products via Admin → Products → Add Product.
